name: Do something at a manual trigger

on:
  workflow_dispatch:
    inputs:
      prop:
        description: "Which prop do you want to see?"
        required: true
        type: choice
        options:
          - name
          - version

jobs:
  print-package-prop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          echo $PROP
          echo $(node -p "require('./package.json').$PROP ")
        env:
          PROP: ${{ inputs.prop }}
