name: My Action Workflow

on: workflow_dispatch

jobs:
  my_action:
    name: My Action Job
    runs-on: ubuntu-latest

    steps:
      - name: My Action Step
        uses: lamartinecabral/my-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          main-branch: "my-action-main"
          dev-branch: "my-action-dev"
