name: Branch name filtering

on:
  pull_request:
    branches:
      - 'thisshouldtrigger*'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo $SKIP_BRANCHES
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(env) }}"

  job2:
    if: github.head_ref == 'thisshouldnottrigger'
    name: Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo

  job3:
    if: github.head_ref != 'thisshouldnottrigger'
    name: Job 3
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo
