name: Branch name filtering

on:
  pull_request:
    branches: ['main']

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo "${{ toJSON(github) }}"

  job2:
    if: github.head_ref == 'thisshouldnottrigger'
    name: Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo

  job3:
    if: github.head_ref != 'thisshouldnottrigger' && github.pull_request.assignee == null
    name: Job 3
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo
