name: Branch name filtering

on:
  pull_request

env:
  SKIP_BRANCHES: '["thisshouldnottrigger"]'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo $SKIP_BRANCHES
          echo "${{ toJSON(github) }}"

  job2:
    if: contains(fromJSON($SKIP_BRANCHES), github.head.ref) == true
    name: Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo

  job3:
    if: contains(fromJSON($SKIP_BRANCHES), github.head.ref) == false
    name: Job 3
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo oi mundo
