name: Branch name filtering

on:
  pull_request:
    branches:
      - '*'

jobs:
  job1:
    if: github.head.ref != 'thisshouldnottrigger'
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          echo "${{ toJSON(github) }}"
