name: Do something if package version changes

on:
  push:
    branches: ["version"]

jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      isequal: ${{ steps.test.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Current version
        run: CUR=$(node -p "require('./package.json').version") && echo "CURRENT=$CUR" >> "$GITHUB_ENV"
      - name: Go to previous commit
        run: git checkout HEAD^
      - name: Previous version
        run: PREV=$(node -p "require('./package.json').version") && echo "PREVIOUS=$PREV" >> "$GITHUB_ENV"
      - id: test
        run: TEST=$(node -p "'$CURRENT' === '$PREVIOUS'") && echo "result=$TEST" >> "$GITHUB_OUTPUT"

  print-false:
    needs: compare
    if: needs.compare.outputs.isequal == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo false

  print-true:
    needs: compare
    if: needs.compare.outputs.isequal == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo true
